#!/usr/bin/env bash
# chkconfig: 2345 90 10

### BEGIN INIT INFO
# Provides:          udp2raw
# Required-Start:    $network $syslog
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Start or stop the udp2raw server
### END INIT INFO

if [ -f /usr/local/bin/udp2raw ]; then
    DAEMON=/usr/local/bin/udp2raw
elif [ -f /usr/bin/udp2raw ]; then
    DAEMON=/usr/bin/udp2raw
fi
NAME=udp2raw
PID_DIR=/var/run
PID_FILE=$PID_DIR/udp2raw.pid
CONF=/etc/udp2raw/udp2raw.conf
LOG_FILE=/var/log/udp2raw/udp2raw.log
RET_VAL=0


[ -x $DAEMON ] || exit 0

if [ ! -d $PID_DIR ]; then
    mkdir -p $PID_DIR
    if [ $? -ne 0 ]; then
        echo "Creating PID directory $PID_DIR failed"
        exit 1
    fi
fi

if [ ! -f $CONF ]; then
    echo "$NAME config file $CONF not found"
    exit 1
fi

check_running() {
    if [ -r $PID_FILE ]; then
        read PID < $PID_FILE
        if [ -d "/proc/$PID" ]; then
            return 0
        else
            rm -f $PID_FILE
            return 1
        fi
    else
        return 2
    fi
}

do_status() {
    check_running
    case $? in
        0)
        echo "$NAME (pid $PID) is running..."
        ;;
        1|2)
        echo "$NAME is stopped"
        RET_VAL=1
        ;;
    esac
}

do_start() {
    if check_running; then
        echo "$NAME (pid $PID) is already running..."
        return 0
    fi

    LOG_DIR="$(dirname "$LOG_FILE")"
    if [ ! -d $LOG_DIR ]; then
        mkdir -p $LOG_DIR
    fi

    $DAEMON --conf-file ${CONF} > ${LOG_FILE} 2>&1 & echo $! > $PID_FILE
    
    # PID=$(ps -ef | grep -v grep | grep -i ${DAEMON} | awk '{print $2}')

    if check_running; then
        echo "Starting $NAME success"
    else
        echo "Starting $NAME failed"
        RET_VAL=1
    fi
}

do_stop() {
    if check_running; then
        kill -9 $PID
        rm -f $PID_FILE
        echo "Stopping $NAME success"
    else
        echo "$NAME is stopped"
        RET_VAL=1
    fi
}

do_restart() {
    do_stop
    do_start
}

case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    echo "Usage: $0 { start | stop | restart | status }"
    RET_VAL=1
    ;;
esac

exit $RET_VAL